#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 52.90.13.9:80 check
        server web2 52.91.165.148:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
